name: Build the latest release using Spack

on:
  workflow_dispatch: {}
  schedule:
  - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-22.04
    name: Build the latest version of the package
    steps:
    - uses: actions/checkout@v4
    - uses: mochi-hpc/mochi-test-build-action@v2
      with:
        build-cache-token: ${{ secrets.GITHUB_TOKEN }}
        push-only-dependencies: false
